In [1]:
"""
Some examples of numerical computations on numpy arrays

https://scipy-lectures.org/intro/numpy/operations.html
"""

import numpy as np

SIZE = 10

In [2]:
# create some 1D numpy array and some slices
np_ints = np.linspace(-SIZE, SIZE - 1, 2 * SIZE)
print(np_ints)
np_evens = np_ints[0::2]
np_odds = np_ints[1::2]
print(np_evens)
print(np_odds)

[-10.  -9.  -8.  -7.  -6.  -5.  -4.  -3.  -2.  -1.   0.   1.   2.   3.
   4.   5.   6.   7.   8.   9.]
[-10.  -8.  -6.  -4.  -2.   0.   2.   4.   6.   8.]
[-9. -7. -5. -3. -1.  1.  3.  5.  7.  9.]


In [3]:
# Operations on single array - reductions
print(np.sum(np_evens))
print(np.min(np_odds))

-10.0
-9.0


In [4]:
# Operations on arrays of same shape
print(np_evens * np_odds)
print(np_odds > np_evens)

[90. 56. 30. 12.  2.  0.  6. 20. 42. 72.]
[ True  True  True  True  True  True  True  True  True  True]


In [5]:
# Operations on arrays of diffent shapes
print(np_evens ** 2)
print(np_evens ** np.full(np_evens.shape, 2))     # manually broadcast

[100.  64.  36.  16.   4.   0.   4.  16.  36.  64.]
[100.  64.  36.  16.   4.   0.   4.  16.  36.  64.]


In [6]:
# Example for broadcast figure
row = np.array([0, 1, 2])
col = np.array([[0], [10],[20],[30]])
print(row)
print(col)
print(row + col)

[0 1 2]
[[ 0]
 [10]
 [20]
 [30]]
[[ 0  1  2]
 [10 11 12]
 [20 21 22]
 [30 31 32]]


In [7]:
# vectorization - creat new vector operations
my_abs = lambda x: x if x > 0 else -x
vec_abs = np.vectorize(my_abs)
print(np.abs(np_odds))
print(vec_abs(np_odds))   # manually vectorize abs

[9. 7. 5. 3. 1. 1. 3. 5. 7. 9.]
[9. 7. 5. 3. 1. 1. 3. 5. 7. 9.]
