In [ ]:
"""
Template for week 5 project in Data Visualization

Create raster images using three types of dynamical systems
"""

import random
import numpy as np
import matplotlib.pyplot as plt

In [ ]:
# Resource paths
PLOTS_PATH = "../docs/week5/plots/"
DATA_PATH = "data/"


In [ ]:
#######################################################################################
# Part 1 - Compute and plot Julia sets


def invert_fun(complex_fun, complex_val):
    """
    Input: np.poly1d object complex_fun and complex complex_val
    
    Output: List of n possible complex solutions to the equation complex_val = complex_fun(inv)
    The roots of complex_poly are the n possible values for complex_fun^(-1)(complex_val)
    """
    
    return []

In [ ]:
def test_invert_fun():
    """ Test invert_fun """
    
    print(invert_fun(np.poly1d([1, -1]), 0))    
    print(invert_fun(np.poly1d([1, 2, 3]), 3))
    print(invert_fun(np.poly1d([1, 0, -4]), 0)) # Different answers between python 3.6 & 3.7
    print(invert_fun(np.poly1d([1, 2, 3], r=True), 0))
    print(invert_fun(np.poly1d([-3.0, 3, 0]), 0.3 + 0.2j))
    
test_invert_fun()

Correct output
~~~~
[1.0]
[-2.0, 0.0]
[-2.0000000000000004, 1.9999999999999996]
[1.0000000000000002, 1.999999999999998, 3.0000000000000018]
[(0.10367460967663507+0.08410597490646866j), (0.8963253903233641-0.08410597490646864j)]
~~~~

In [ ]:
def julia_set(lmbd, z_0, num_returned, num_dropped, seed=None):
    """
    Input: complex lmbd, z_0, integers num_returned, num_dropped,
    optional integer seed
    
    Output: List of complex numbers of length num_returned
    generated by Julia iteration with given lmbd
    """
    
    if seed:
        random.seed(seed)

    # Remember to use random.choice() when selecting an inverse
    
    return []

In [ ]:
def test_julia_set():
    """ Test julia_set() """
    
    lmbd = 3
    z_0 = 0.3 + 0.2j
    print(julia_set(lmbd, z_0, 10, 0, 1))
    print()
    print(julia_set(lmbd, z_0, 10, 5, 1))
    print()
    lmbd = 2 + 1.0j
    z_0 = -0.2 + 0.3j
    print(julia_set(lmbd, z_0, 10, 0, 1))
    

test_julia_set()

Correct output
~~~~
[(0.3+0.2j), (0.10367460967663507+0.08410597490646866j), (0.034865585614995406+0.030136799279720974j), (0.9883481598313641-0.010285284747848681j), (0.493919787238025-0.28193324670511233j), (0.825820029026002+0.14421726801547266j), (0.6204943873886895-0.19947992480659082j), (0.7474326064736576+0.1343665033006527j), (0.6510840950633332-0.14822484926284196j), (0.28509105593250883-0.11495166779121475j)]

[(0.825820029026002+0.14421726801547266j), (0.6204943873886895-0.19947992480659082j), (0.7474326064736576+0.1343665033006527j), (0.6510840950633332-0.14822484926284196j), (0.28509105593250883-0.11495166779121475j), (0.10338550564224777-0.04830537353295625j), (0.9645841879521861+0.017329250107097124j), (0.489209610888019+0.26766489337960764j), (0.8251913075981272-0.13718329648096955j), (0.6163666227810709+0.19648144975250936j)]

[(-0.2+0.3j), (-0.04029949867157211+0.1480660267068451j), (0.008879610432771818+0.0685028679794222j), (0.9831674493944611-0.026517954735288757j), (0.264415995902002-0.4398445313944147j), (1.028301113868141+0.21656306009159573j), (0.6266947571262835+0.4697708154503252j), (0.5969913338285733-0.32255136765858583j), (0.9095207479672995+0.3033043076110339j), (0.42851921689038075-0.42376722745286827j)]
~~~~

In [ ]:
def plot_julia(julia_points, lmbd):
    """
    Input: List of complex numbers that lie on the Julia set for given lmbd
    
    Output: Scatter plot of complex number in list julia_points
    """
    
    fig, axs = plt.subplots()
    return fig

In [ ]:
def test_plot_julia():
    """ Test plot_julia() """
    
    lmbd = 3
    z_0 = 0.2 + 0.3j
    julia_points = julia_set(lmbd, z_0, 2000, 20, 1)
    plot_julia(julia_points, lmbd)
    
    lmbd = 2 + 1.0j
    z_0 = 0.2 + 0.3j
    julia_points = julia_set(lmbd, z_0, 2000, 20, 1)
    plot_julia(julia_points, lmbd)

test_plot_julia()

In [ ]:
##############################################################################
# Part 2 - Compute and plot Mandelbrot sets

MAX_ITERS = 20


def iterate_mandel(z_0):
    """
    Input: complex z_0
    
    Output: number of iterations for Mandelbrot function f(z) = z ** 2 + z_0 to diverge,
    maximum number of iterations is capped at MAX_ITERS
    """
    
    return []

In [ ]:
def test_iter_mande1():
    """ Test iterate_mandel() """
    
    print(iterate_mandel(4))
    print(iterate_mandel(2))
    print(iterate_mandel(-2))
    print(iterate_mandel(1 + 1j))
    print(iterate_mandel(0.3 + 0.3j))
    print(iterate_mandel(0.3 - 0.3j))
    
test_iter_mande1()

Correct output
~~~~
0
1
20
1
20
20
~~~~

In [ ]:
def mandel_table(real_values, imag_values):
    """
    Input: arrays real_values, imag_values of floats
    
    Output: 2D numpy array indicating number of iterations for
    divergence of Mandelbrot iteration initialized at
    corresponding complex values
    """
    
    return np.array([])

In [ ]:
def test_mandel_table():
    """ Test mandel_table() """
    
    range1 = [-2.25, 0.75, -1.25, 1.25]
    range2 = [-1.5, -1.0, -0.1, 0.5]
    
    real_values = np.linspace(range1[0], range1[1], 7)
    imag_values = np.linspace(range1[2], range1[3], 8)
    print(mandel_table(real_values, imag_values))
    
    real_values = np.linspace(range2[0], range2[1], 11)
    imag_values = np.linspace(range2[2], range2[3], 11)
    print(mandel_table(real_values, imag_values))

test_mandel_table()

Correct output
~~~~
[[ 0  0  1  2  2  1  1]
 [ 0  1  2  3  8  3  1]
 [ 0  2  3  5 20 20  2]
 [ 0  3 16 18 20 20  2]
 [ 0  3 16 18 20 20  2]
 [ 0  2  3  5 20 20  2]
 [ 0  1  2  3  8  3  1]
 [ 0  0  1  2  2  1  1]]
[[ 6  7 11 12 13 20 20 20 20 20 20]
 [ 9 10 14 20 20 20 20 20 20 20 20]
 [10 15 20 20 20 20 20 20 20 20 20]
 [ 6  8 10 20 18 20 20 20 20 20 20]
 [ 5  6 11  8 10 14 20 20 20 20 20]
 [ 4  4  5  6  7 10 17 20 20 20 20]
 [ 4  4  4  5  6  8 12 20 20 20 20]
 [ 4  4  4  5  6 13 17 20  9 11 14]
 [ 3  3  4  5  6 20  7  6  6  7  7]
 [ 2  3  3  3  6  5  5  5  5  4  4]
 [ 2  2  2  2  3  3  4  4  4  4  4]]
~~~~

In [ ]:
def plot_mandelbrot(real_values, imag_values):
    """
    Input: lists (or numpy arrays) real_values and imag_values
    
    Output: matplotlib figure of image plot of mandel_table()
    applied to real_values, imag_values
    """
    
    fig, axs = plt.subplots()
    return fig

In [ ]:
def test_plot_mandelbrot():
    """ Test plot_mandelbrot() """
    
    range1 = [-2.25, 0.75, -1.25, 1.25]
    range2 = [-1.5, -1.0, -0.1, 0.5]
    
    real_values = np.linspace(range1[0], range1[1], 101)
    imag_values = np.linspace(range1[2], range1[3], 101)
    plot_mandelbrot(real_values, imag_values)
    
    real_values = np.linspace(range2[0], range2[1], 301)
    imag_values = np.linspace(range2[2], range2[3], 301)
    plot_mandelbrot(real_values, imag_values)
    
test_plot_mandelbrot()

In [ ]:
#########################################################################################
# Part 3 - Compute and plot Newton basins 

EPSILON = 0.000001

def newton_index(roots, z_0):
    """
    Input: List of complex roots, complex initial value z_0
    
    Output: Index of root in roots to which Newton iteration with initial
    value z_0 converges (with tolerance EPSILON)
    
    NOTE: If the iteration encounters a zero derivative, return len(roots)
    """
    
    return 0

In [ ]:
def test_newton_index():
    """ Test newton_index() """
    
    z_0 = 0
    roots = [1]
    print(newton_index(roots, z_0))
    
    z_0 = 2
    roots = [-3, 4]
    print(newton_index(roots, z_0))
    
    z_0 = 0
    roots = [-2, 2]
    print(newton_index(roots, z_0))
    
    z_0 = 0.2 + 0.3j
    roots = [0.5 + 0.5j, 0.5 - 0.5j, -0.5 + 0.5j, -0.5 - 0.5j]
    print(newton_index(roots, z_0))
    
    z_0 = -0.2 - 0.3j
    roots = [0.5 + 0.5j, 0.5 - 0.5j, -0.5 + 0.5j, -0.5 - 0.5j]
    print(newton_index(roots, z_0))
    
    
test_newton_index()

Correct output
~~~~
0
1
2
0
3
~~~~

In [ ]:
def newton_table(roots, real_values, imag_values):
    """
    Input: List of complex numbers roots, two lists of floats that define a grid
    of complex numbers
    
    Output:  2D numpy array of Newton indices where z_0 takes on values in
    the grid of complex numbers
    """
    
    return np.array([])

In [ ]:
def test_newton_table():
    """ Test newton_table() """
    
    samples = 7
    roots = [0.5 + 0.5j, 0.5 - 0.5j, -0.5 + 0.5j, -0.5 - 0.5j]
    real_values = np.linspace(-1, 1, samples)
    imag_values = np.linspace(-1, 1, samples)
    print(newton_table(roots, real_values, imag_values))
    
    samples = 11
    roots = [-0.5j, 0.2 + 0.3j, -0.3 + 0.2j]
    real_values = np.linspace(-1, 1, samples)
    imag_values = np.linspace(-1, 1, samples)
    print(newton_table(roots, real_values, imag_values))
    
test_newton_table()

Correct output
~~~~
[[3 3 3 4 1 1 1]
 [3 3 3 4 1 1 1]
 [3 3 3 4 1 1 1]
 [4 4 4 4 4 4 4]
 [2 2 2 4 0 0 0]
 [2 2 2 4 0 0 0]
 [2 2 2 4 0 0 0]]
[[0 0 0 0 0 0 0 0 0 0 0]
 [2 0 0 0 0 0 0 0 0 0 0]
 [1 2 0 0 0 0 0 0 0 0 2]
 [2 2 1 1 0 0 0 0 2 1 2]
 [2 2 2 2 1 2 1 2 2 2 1]
 [2 2 2 2 2 2 1 1 1 1 1]
 [2 2 2 2 2 1 1 1 1 1 1]
 [2 2 2 2 2 1 1 1 1 1 1]
 [2 2 2 2 2 1 1 1 1 1 1]
 [2 2 2 2 2 1 1 1 1 1 1]
 [2 2 2 2 0 1 1 1 1 1 1]]
~~~~

In [ ]:
#########################################################################################
# Student code for plotting Newton basins (peer-graded)

def plot_newton(roots, real_values, imag_values):
    """
    Input: List of complex numbers roots, two lists of floats that define a grid
    of complex numbers
    
    Output: matplotlib figure of mage plot of mandel_table()
    applied to roots, real_values, imag_values
    """
    
    fig, axs = plt.subplots()
    return fig

In [ ]:
def test_plot_newton():
    """ Test plot_newton """
    
    # Simple test case - not required
    samples = 21
    roots = [0.801 + 0.8j, -0.298 - 0.202j]
    real_values = np.linspace(-1, 1, samples)
    imag_values = np.linspace(-1, 1, samples)
    print(newton_table(roots, real_values, imag_values))
    plot_newton(roots, real_values, imag_values)
    
    # Required test case
    samples = 301
    roots = [0.5 + 0.5j, 0.5 - 0.5j, -0.5 + 0.5j, -0.5 - 0.5j]
    real_values = np.linspace(-1, 1, samples)
    imag_values = np.linspace(-1, 1, samples)
    plot_newton(roots, real_values, imag_values)
    
    # Required test case
    roots = [-0.5j, 0.2 + 0.3j, -0.3 + 0.2j]
    real_values = np.linspace(-1, 1, samples)
    imag_values = np.linspace(-1, 1, samples)
    plot_newton(roots, real_values, imag_values)
    
    
test_plot_newton()